### ISSUE TITLE
Met problem about `debug_traceTransaction` for RPC endpoint when `TransactionReceipt.return_value` is used. 

### ISSUE THREAD

**Issue by Techget** [brownie-mix/dao-mix#1]
Dear developer, 

Context:
   Recently, I tried to use this implementation and deploy it to Polygon(Mumbai)  with Infura as the node provider and Brownie.

   Related doc for brownie [TransactionReceipt.return_value](https://eth-brownie.readthedocs.io/en/stable/api-network.html#TransactionReceipt.return_value) 

Problem:
   Received error message as 
   ```
   RPCRequestError: Accessing `TransactionReceipt.return_value` on a confirmed transaction requires the `debug_traceTransaction` RPC endpoint, but the node client does not support it or has not made it available.
   ```
  
Question:
- Do you have some ideas about the workaround we can use in this case? 
- Do you consider to implement a version where it records the latest `proposal_id` as a state so that we can query the Governor contract instead? 

Thanks

**Comment by PatrickAlphaC** [comment]
Ah yes, this is due to the Mumbai RPC_URL that you're using not being able to handle that.

You can get the return value from:
1. A better RPC URL
2. An event that is emitted
3. Using `call`

I'd rather get the `proposalId` right from an event rather than saving it as state. You can see an example of getting events here: https://github.com/PatrickAlphaC/brownie-events-logs

If you do this successfully, could you make a PR? 

More info: 

https://ethereum.stackexchange.com/questions/92603/how-to-get-the-return-value-of-a-transaction-instead-of-the-transaction-receipt

**Comment by Techget** [comment]
Thanks for the information, have created a pull request (https://github.com/brownie-mix/dao-mix/pull/2).
